import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { APP_PRODUCT_NAME, APP_PRODUCT_SUBTITLE, APP_VERSION_TEXT, ORGANIZATION_PROFILES_BY_SLUG, ORGANIZATION_SLUGS, getOrganizationAccessLabel, getOrganizationUnavailableTitle } from "@sige/contracts";
import { useAuth } from "./AuthContext";
import intellilawLogo from "../../assets/intellilaw-logo.svg";
import legalFlowLogo from "../../assets/legalflow-logo.svg";
import rusconiLogo from "../../assets/rusconi-logo-2025.jpg";
export function EntryPage() {
    const { user } = useAuth();
    const intellilawOrganization = ORGANIZATION_PROFILES_BY_SLUG[ORGANIZATION_SLUGS.INTELLILAW];
    const legalFlowOrganization = ORGANIZATION_PROFILES_BY_SLUG[ORGANIZATION_SLUGS.LEGALFLOW];
    const rusconiOrganization = ORGANIZATION_PROFILES_BY_SLUG[ORGANIZATION_SLUGS.RUSCONI_CONSULTING];
    const getAccessPath = (organizationSlug) => user?.organizationSlug === organizationSlug ? "/app" : `/intranet-login?organization=${organizationSlug}`;
    return (_jsx("main", { className: "entry-page", children: _jsx("div", { className: "entry-shell", children: _jsxs("section", { className: "entry-card", children: [_jsx("div", { className: "entry-accent", "aria-hidden": "true" }), _jsxs("div", { className: "entry-brand", children: [_jsx("div", { className: "entry-brand-logo-shell", children: _jsx("img", { className: "entry-brand-logo", src: intellilawLogo, alt: `Logo ${intellilawOrganization.name}` }) }), _jsx("p", { className: "entry-brand-name", children: intellilawOrganization.name.toUpperCase() })] }), _jsx("h1", { className: "entry-title", children: APP_PRODUCT_NAME }), _jsx("p", { className: "entry-version", children: APP_VERSION_TEXT }), _jsx("p", { className: "entry-subtitle", children: APP_PRODUCT_SUBTITLE }), _jsxs("div", { className: "entry-actions", children: [_jsxs("div", { className: "entry-option", children: [_jsx("div", { className: "entry-option-logo-shell", children: _jsx("img", { className: "entry-option-logo", src: intellilawLogo, alt: intellilawOrganization.name }) }), _jsx(Link, { to: getAccessPath(intellilawOrganization.slug), className: "entry-button entry-button-primary", children: getOrganizationAccessLabel(intellilawOrganization) })] }), _jsxs("div", { className: "entry-option", children: [_jsx("div", { className: "entry-option-logo-shell", children: _jsx("img", { className: "entry-option-logo", src: legalFlowLogo, alt: legalFlowOrganization.name }) }), _jsx("button", { type: "button", className: "entry-button entry-button-disabled", disabled: true, "aria-disabled": "true", title: getOrganizationUnavailableTitle(legalFlowOrganization), children: getOrganizationAccessLabel(legalFlowOrganization) })] }), _jsxs("div", { className: "entry-option", children: [_jsx("div", { className: "entry-option-logo-shell", children: _jsx("img", { className: "rusconi-logo entry-option-logo", src: rusconiLogo, alt: rusconiOrganization.name }) }), _jsx(Link, { to: getAccessPath(rusconiOrganization.slug), className: "entry-button entry-button-primary", children: getOrganizationAccessLabel(rusconiOrganization) })] })] })] }) }) }));
}
