import { COMMISSION_SECTIONS, ORGANIZATION_PROFILES_BY_SLUG, ORGANIZATION_SLUGS } from "@sige/contracts";

const RUSCONI_CONSULTING_COMMISSION_RECEIVERS = [
  "Israel Vidal"
] as const;

const RUSCONI_CONSULTING_ORGANIZATION_ID =
  ORGANIZATION_PROFILES_BY_SLUG[ORGANIZATION_SLUGS.RUSCONI_CONSULTING].id;

export function getRequiredCommissionReceiverNames(organizationId: string) {
  return [
    ...COMMISSION_SECTIONS,
    ...(organizationId === RUSCONI_CONSULTING_ORGANIZATION_ID ? RUSCONI_CONSULTING_COMMISSION_RECEIVERS : [])
  ];
}
